### ISSUE TITLE
add the stuff we used on documentation

### ISSUE THREAD

**Issue by moiSentineL** [moiSentineL/flomo#56]

**Comment by moiSentineL** [comment]
- python (lol)
- rich
- click
- blessed
- playsound

- notify-send
- paplay

**Comment by Jonak-Adipta-Kalita** [comment]
@moiSentineL if you are planning on making a more complicated documentation, coz.... flomo has turned out to be way more fking complecated than we wanted it to be, you can use [docusaurus](https://docusaurus.io/). trust me, its the fastest ssg I have ever seen. ITS FASTER THAN ASTRO

**Comment by moiSentineL** [comment]
> @moiSentineL if you are planning on making a more complicated documentation, coz.... flomo has turned out to be way more fking complecated than we wanted it to be, you can use [docusaurus](https://docusaurus.io/). trust me, its the fastest ssg I have ever seen. ITS FASTER THAN ASTRO (Lemme know, if you want proof of it :D)

come on, are we making such a big program?

**Comment by moiSentineL** [comment]
added https://github.com/moiSentineL/flomo/pull/69/commits/e3915240dcf4877c56f012f4c4b128afc53be46c
